### ISSUE TITLE
No scores Just times

### ISSUE THREAD

**Issue by teegray1124** [jclarke0000/MMM-MyScoreboard#60]
There arent any scores getting pulled. I only see start times. Even when the game is on. Any help please?

**Comment by joepalma** [comment]
I started having this issue yesterday. Come today it's not just start times but the games haven't update, it's still showing games for Aug 11th.

**Comment by teegray1124** [comment]
my games are updated, but no scores.

**Comment by yguns31** [comment]
Had a quick look and the URL for the Sportsnet ticker has changed.

I think if on line 112 of SNET.js, the URL is changed from:

https://d290qmen6zswb.cloudfront.net/ticker

to

https://mobile-statsv2.sportsnet.ca/ticker

that should fix it.

**Comment by teegray1124** [comment]
> Had a quick look and the URL for the Sportsnet ticker has changed.
> 
> I think if on line 112 of SNET.js, the URL is changed from:
> 
> https://d290qmen6zswb.cloudfront.net/ticker
> 
> to
> 
> https://mobile-statsv2.sportsnet.ca/ticker
> 
> that should fix it.

That worked thanks

**Comment by joepalma** [comment]
Worked like a charm, thank you!

**Comment by VetteManiac** [comment]
I changed SNET.js, line 112 from https://d290qmen6zswb.cloudfront.net/ticker to https://mobile-statsv2.sportsnet.ca/ticker
and then I restarted MM and now nothing shows up. Changed it back, restarted MM and still nothing. I do get this error before and after the change
[13.08.2022 20:21.54.826] [LOG]   [MMM-MyScoreboard] 13-Aug-22 20:21 ** ERROR ** Couldn't retrieve data for provider SNET: null

**Comment by Robert-litts** [comment]
@yguns31 I updated the URL on line 112 of SNET.js to the link you provided, but am still seeing the same error as @VetteManiac. Was there anything else that needed to be done aside from update the SNET.JS? 

"14-Aug-22 16:25 ** ERROR ** Couldn't retrieve data for provider SNET: null"

**Comment by yguns31** [comment]
Did you leave the rest of the querystring as is?  

The changes I made look like this:

https://github.com/jclarke0000/MMM-MyScoreboard/pull/61/files

**Comment by shroomzzz** [comment]
@yguns31 Nice call on putting up a PR. I am also facing the same problem as Robert now tho hehe

All I did was do a Find+Replace on Line 112

`https://d290qmen6zswb.cloudfront.net/ticker`

`https://mobile-statsv2.sportsnet.ca/ticker`

keeping the appended `?day=" + this.gameDate.format("YYYY-MM-DD")`

The module throws no errors in console and just displays my header text and "Loading" on the UI :(

**Comment by Robert-litts** [comment]
@yguns31 Thank you! I was missing the remainder of the querystring. I had only included "https://mobile-statsv2.sportsnet.ca/ticker" but needed "https://mobile-statsv2.sportsnet.ca/ticker/ticker?day=". 

Pull request 61 (https://github.com/jclarke0000/MMM-MyScoreboard/pull/61/files) is spot on and my display is back in business. Thanks for the help all.

**Comment by sigel** [comment]
> Had a quick look and the URL for the Sportsnet ticker has changed.
> 
> I think if on line 112 of SNET.js, the URL is changed from:
> 
> https://d290qmen6zswb.cloudfront.net/ticker
> 
> to
> 
> https://mobile-statsv2.sportsnet.ca/ticker
> 
> that should fix it.

Thank you this worked!
Line 112:
var url = "https://mobile-statsv2.sportsnet.ca/ticker?day=" + this.gameDate.format("YYYY-MM-DD");

**Comment by kylewilliams321** [comment]
Are we putting in a fix for a future release?

**Comment by jclarke0000** [comment]
This is now fixed in master.  do a `git pull` for the up to date code.

**Comment by Demost9** [comment]
This issue is happening to me now. I installed the module yesterday, and it is the latest version. Looks great but only showing start times not the scores from the day before. Is there a timing editor? Any way to fix it?
